### ISSUE TITLE
New Version message re-appears after on-screen rotation if user has selected "See Message Later"

### ISSUE THREAD

**Issue by davirec** [zathras/JRPN_Android#12]
When I perform these sequences of events, a message appears after on-screen rotation:

1. Go to the Main activity
2. Tap in See message later
3. A fragment similar to this will appear:

Before rotation:
<img src="https://user-images.githubusercontent.com/3637419/158030860-a1d9cdd9-7c83-46a6-b138-9c78cfde9a75.png" width=30% height=30%>

4. Force the pause from the activity and then return to the activity (double rotation). Note that a message appears. 
Note: the pause from activity can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

The expected behavior is the return to the previous image.

However, a message appears.

After rotation:

<img src="https://user-images.githubusercontent.com/3637419/158030857-d8037357-1b95-41ef-84c6-feb3e316a212.png" width=30% height=30%>

Device:
- Device: Moto G30 with OS: Android 11
- Version: 1.1.5
- Device language: English

**Data loss**

A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values. This issue is related to the activity's lifecycle (1). When a screen rotation occurs, the activity is destroyed and resumed. Data loss will happen if the developer does not save the variables before the destruction and restore them after creation. To avoid this, the developers have to implement both the logic necessary to save the activity state in the onSaveInstanceState() callback method and the logic to resume its state in the onRestoreInstanceState() callback method.
Another way to avoid data loss problems is to use the view model, designed to store and manage UI-related data in a lifecycle-conscious way (2).

1. https://developer.android.com/guide/components/activities/activity-lifecycle 
2. https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by zathras** [comment]
That does indeed look like a bug...  But, if I may, why are you using the legacy version?  The new Flutter version is IMHO better in all respects, and a complete rewrite (as opposed to being a port of WRPN)...   https://jrpn.jovial.com/

**Comment by davirec** [comment]
Thanks for the tip.

**Comment by davirec** [comment]
Hi Zathras,
in this activity, we found other bugs: disabled a feature on the display, list menu disappeared, pop up menu disappeared, lost calculator data, lost activity state, and lost message fragment.

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.


<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159187488-53cf9231-c568-4352-a957-bbd9b796bd54.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159187487-be94c99c-d616-4055-a8dd-be392eb70c1c.png" width=20% height=20%>
</figure>

</div> 
 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159187522-298356d2-1e2b-41f6-a407-3c659e354473.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159187518-6f205ab1-a0a5-4cb3-817e-951e30a04bb5.png" width=20% height=20%>
</figure>

</div> 
 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159187578-a80b6290-c112-49fa-98cc-769cd02fb588.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159187576-b504a654-b4cd-4803-a6dd-41b24c380e85.png" width=20% height=20%>
</figure>

</div> 
 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159187626-adb63e82-8190-4b4d-bbda-3a12021d2d27.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159187624-aa092483-9d57-4785-ad2f-d5c2cf13d935.png" width=20% height=20%>
</figure>

</div> 
 


<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159187684-a994aec8-5f36-4760-9f6f-f03c0ee1e843.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159187681-adf03b37-7fd2-4721-a8ac-935b340c6d83.png" width=20% height=20%>
</figure>

</div>

**Comment by zathras** [comment]
OK...  Could you answer my question, please?  Why are you using the (largely unsupported) legacy version, instead of the current version?

Take a look at the description of this app.  It was kind of a stopgap UI improvement to the WRPN simulator, but now there's something that I consider to be much better available.

**Comment by davirec** [comment]
Hi Zathras,
This version is available on the F-droid app store. I'm working with apps hosted on F-droid to check for data loss after double screen rotation for a software engineering experiment. This app was selected following my search criteria.

**Comment by zathras** [comment]
Yeah, I figured this was some kind of automated thing.

So, I take you you don't care if this gets fixed or not?  Because it's not a terribly interesting bug.  It's in the part of the app that I didn't write, and while it _technically_ qualifies as "data loss," it doesn't involve the loss of anything interesting or valuable.  It's a pretty superficial issue that I'd have trouble calling anything other than minor and cosmetic.  Coupled with the fact that this app has been superseded, this doesn't look like it's worth worrying about.
