### ISSUE TITLE
Activity memory leak caused by anonymous threads

### ISSUE THREAD

**Issue by cuixiaoyiyi** [zathras/JRPN_Android#13]
An anonymous inner class will hold a reference to the this pointer of the outer class and will not be released until the thread ends.

There are 2 Threads in fmMain.

[They](https://github.com/zathras/JRPN_Android/blob/master/app/src/main/java/com/jovial/jrpn/fmMain.java#L1249) will hold the Activity and prevent its timely release.

**Comment by zathras** [comment]
This looks like an issue that was created by some sort of automated audit process.

Holding on to memory as long as the application is running isn't a "leak."  The fact that an automated audit tool detected something related to thread creation might or might not indicate an area for concern when the application is terminated by the Android system.  If there's no actual observation of a real problem in the real application, the results of an automated audit like this appears to be is of scant value.

If you'd like to submit an issue, please describe an actual, observed problem, and not a generic description of something that _might_ be an issue based on an automated audit.

One might also question the value of auditing an application that has been superseded for years.

(BTW, the thread your audit identified is very short lived, so your audit is wrong in this case.)
