### ISSUE TITLE
Unable to save orientation on beta 3

### ISSUE THREAD

**Issue by johanw666** [zathras/JRPN_Android#2]
The release "Update API to 29" somehow is unable to save the orientation. I fixed it to  landscape because I disabled screen rotation, and this worked as it should on beta 2. I reinstalled the beta 2 version now.

Device: Sony Z3 Compact, Android 6.0.1.

**Comment by zathras** [comment]
Thanks for the report.  It looks like this was a non-backwards-compatible change in Android.  The app was originally using Context.getExternalFilesDir(), which I think was the only place to store files back when Emmet wrote the original.  Nowadays, getFilesDir() is preferred -- it stores the config files inside the app's sandbox.  To use getExternalFilesDir(), new apps have to request that permission.  I guess the old version didn't need to ask, due to some kind of legacy grandfathering policy in Android?

Anyway, the fix is to use the newer getFilesDir().  This does mean that the old config files will be orphaned -- and I'd have to request the permission to even try to clean them up, which would just add more confusion.  So, I guess I'll leave that alone.  They're small, anyway!

This will be in 1.1.1, which I'll publish now.  (Of course, I only noticed this issue when I was in the middle of publishing 1.1 :-) )

**Comment by johanw666** [comment]
You can still get files in the old location but then you'll have to go through the "request storage access permission" dialog first (and use a fallback if the user refuses). Perhaps this permission would be useful in the future if a method for saving and loading programs would be implemented (hint at feature request).

But entering 5 settings again is no big deal of course and not unreasonable when dealing with a beta version. Which works very well anyway, thanks for taking on where the previous version had stopped. I can clean them up manuall;y anyway.

**Comment by zathras** [comment]
Right, I could have just requested the permission, but app-local storage really is the right place for this kind of thing.  Besides, requesting the permission would lead some to question why a calculator wants that permission in the first place -- I know I'd be at least a little suspicious of a calculator that wanted a permission broad enough to access all my photos, and other files.

**Comment by zathras** [comment]
About saving and loading programs...  Doesn't "save state as" and "Open Existing State..." do that?  I confess I've never tried programming JRPN, or a 16c for that matter (but I was pretty good at programming my physical HP 15C when I was an undergraduate :-) ).  Anyway, try Menu -> File -> Save State As...

I haven't touched that part of the code, other than the recent change to store the file in the app's file area.

**Comment by johanw666** [comment]
Yes, Save State does that, at least as far as I can see. I'm still learning how to use RPN calculators; after I came along all these nice emulators and concluded I have a new hobby. I'll have to pick up from where I started at university many years ago, programming polar graphs on a Casio FX8000G.

However, the relevant issue here I was talking about is to be able to exchange these states with other devices or users. Sure, I can do that now because I have a rooted device and can access the /data/data folders, but an export option to the internal or removable storage would be nice. No hurry for me, but just an idea for a new feature.

**Comment by zathras** [comment]
Oh, I see.  Makes sense; good idea.  Thanks.
    
    Hmmm...  It seems like there ought to be some sort of generic file
    export intent I could generate, that would get picked up by the file
    explorer, and dropbox, and hopefully an e-mail program. 
    
    Note to self:  a quick DuckDuckGo lead me to Intent.ACTION_SEND,
    and  https://developer.android.com/training/sharing/send, and of
    course sharing/receive.
    
    On 11/23/19 4:35 PM, johanw666 wrote:
    
    
      
      Yes, Save State does that, at least as far as I can see. I'm
        still learning how to use RPN calculators; after I came along
        all these nice emulators and concluded I have a new hobby. I'll
        have to pick up from where I started at university many years
        ago, programming polar graphs on a Casio FX8000G.
      However, the relevant issue here I was talking about is to be
        able to exchange these states with other devices or users. Sure,
        I can do that now because I have a rooted device and can access
        the /data/data folders, but an export option to the internal or
        removable storage would be nice. No hurry for me, but just an
        idea for a new feature.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zathras/JRPN_Android/issues/2?email_source=notifications\u0026email_token=AE6M4GYBWUSJS6EXEQ2NLX3QVHD3LA5CNFSM4JQWDSK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFAA5JA#issuecomment-557846180",
"url": "https://github.com/zathras/JRPN_Android/issues/2?email_source=notifications\u0026email_token=AE6M4GYBWUSJS6EXEQ2NLX3QVHD3LA5CNFSM4JQWDSK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFAA5JA#issuecomment-557846180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
