### ISSUE TITLE
Overriding decimal point versus comma from locale (was "Version 1.1 Radix error").

### ISSUE THREAD

**Issue by caroper** [zathras/JRPN_Android#5]
Default Radix (Digit Separator) is a Comma but should be a Point:

From the HP-16C documentation - Digit Separators
The HP-16C is set to use a period as a radix mark (separating
integer and fractional parts of a number) and a comma between
groups of three integer digits.

The documented procedure to change radix is also not functional:

You can reverse this setting to conform to the numerical convention in many countries. This
procedure ( ON / . ) will reverse the current setting:
1. Turn off the calculator.
2. Press and hold ON
3. Press and hold .
4. Release ON , then release .

This sequence closes the emulation when ON is released.

**Comment by zathras** [comment]
In the US locale, the default is, in fact, a decimal point.  I'm guessing your phone's locale is somewhere else, like Europe?

In principle, it wouldn't be too hard to override the Android locale, and switch presentation based on the key sequence described.  If that were done, it would make sense to add a checkbox to the options menu, too.  Of course, the emulation of 1 the 16C would still be incomplete, in that the appearance of the LCD display isn't emulated, and some care would be required with font size to make sure there's enough room for the commas for decimal numbers over 999.

**Comment by caroper** [comment]
I am in South Africa where the default is also a decimal point but I do not normally have android Location Services running unless using the device for navigation.

I agree that a checkbox on the options menu is probably the best solution.
Not many people would know to press the ON Key or read the documentation to find it.
But as a 30+ year HP16C user It was natural instinct for me to try the keystroke method.

**Comment by zathras** [comment]
Deployed to Google app store as 1.1.4

**Comment by caroper** [comment]
👍 - Thanks that has bugged me for a long time but it was still the best
RPN calculator ever.
