### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by IzzySoft** [zathras/JRPN_Android#6]
You've opened a [packaging request](https://gitlab.com/fdroid/rfp/-/issues/1280) with F-Droid a little while ago. Unfortunately, while trying to package your app I've run into a problem: build fails with

```
> Task :app:compileReleaseJavaWithJavac
/builds/IzzySoft/fdroiddata/build/com.jovial.jrpn/app/src/main/java/com/jovial/jrpn/fmAbout.java:22: error: cannot find symbol
        tvDate.setText("Built:  " + BuildConfig.BUILD_TIME.toLocaleString());
                                               ^
  symbol:   variable BUILD_TIME
  location: class BuildConfig
1 error
> Task :app:compileReleaseJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Any hints?

**Comment by IzzySoft** [comment]
@zathras you're still there? F-Droid inclusion is currently hanging with the above problem (compilation error).

**Comment by zathras** [comment]
Hi Izzy,
    
    Yes, still here.  Sorry for the delay.  I think I will come around
    to this in the next week or two.  The hold-up, quite honestly, is
    mostly the overhead in bumping up all the versions that Google is
    probably going to force me to bump up when I go to re-build!  :-)
    
    When I have made the changes, do I need to re-submit to F-Droid, or
    is a putback/release to github sufficient?
    
    Thanks,
    
    Bill
    
    On 2/9/21 10:59 AM, Izzy wrote:
    
    
      
      @zathras
        you're still there? F-Droid inclusion is currently hanging with
        the above problem (compilation error).
      —
        
      
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zathras/JRPN_Android/issues/6#issuecomment-776165890",
"url": "https://github.com/zathras/JRPN_Android/issues/6#issuecomment-776165890",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by IzzySoft** [comment]
Just let me know when you've fixed it and there's a tag availeble with the fixed version. I was processing your RFP, opening a merge request to add your app and got stuck at that error. So I'd then just switch to the fixed version and hope it builds, effectively making your app available at F-Droid as a result.

Thanks!

**Comment by zathras** [comment]
Addressed by https://github.com/zathras/JRPN_Android/commit/4e6347d366d6f6e4595f260bd4b27607efc97727 , but I still need to put together a release.

**Comment by IzzySoft** [comment]
That's great news, thanks! :smiley: Looking forward to the release then – and to your "ping" when it's there. :crossed_fingers:

**Comment by zathras** [comment]
Hi Izzy,

Just to let you know, I think I've finished all the substantive changes for a new release.  Before I declare it final, though, I want to do a test deployment through the play store to my phone, and make sure everything looks OK in that production environment.  I'm waiting for Google to turn an administrative crank that will let me do this -- shouldn't be more than a couple of days.

If you're curious, the original problem here appears to be that Google made a backwards-incompatible change.  Specifically, I think they removed an API when building in release mode.  It wasn't hard to fix or anything, but there were a number of hoops to jump through, like updating the dev environment, and bumping up some version numbers and such.

**Comment by IzzySoft** [comment]
Thanks for the heads-up, Zathras! :crossed_fingers: for the deployment then. And yes, those changes are a pain, not only with G (yes, Moz, looking at you)… I keep waiting for your Go then patiently :smile:

**Comment by zathras** [comment]
All done!  Hope this works with F-Droid.

**Comment by IzzySoft** [comment]
@zathras urn… issues with your caps lock maybe, but could you please fix the tag name? `1_1_3` => `1.1.3`?

**Comment by IzzySoft** [comment]
Oh – there it is! Build running…

**Comment by IzzySoft** [comment]
Aaaand – merged! Thanks a lot! All went like a breeze this time. Give it about a week, and JRPN should show up at F-Droid.
