### ISSUE TITLE
Unable to save orientation

### ISSUE THREAD

**Issue by johanw666** [zathras/JRPN_Android#8]
When I change the orientation from "auto" to "landscape", it is reset to auto on next app restart. FYI, my phonenhas screen rotation off.

This happens on an Android 6 and 10 device.

Edit: you updated targetSDK to 29, that prevents write access to the file system outside your /data/data folder. If you want to keep it you need to add android:requestLegacyExternalStorage="true" to the \<appplication\> section in your AndroidManifest.xml.

Edit2: After building it seemed that didn't help. What did help however was to delete all appdata and then setting it up. The app data from 1.1.1 somehow prevented the app from storing its settings.

**Comment by zathras** [comment]
The original code was dumping the configuration when the calculator version number changed.  That's overly strict, so I changed it to be the configuration file version number, which I fixed at "1.3.3".  This way, if the calculator version number increases, the config file version can stay the same.

No reason to spin a new release for this - the version number is now effectively 1.1.3 with the new release.
